name: segura_manegerial
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  rflutter_alert: ^1.0.3
  modal_progress_hud: ^0.1.3  
  gradient_app_bar: ^0.1.3
  firebase_storage_image: ^0.4.0
  firebase_storage: ^3.1.0
  image_picker: ^0.6.2+3
  cached_network_image: ^2.0.0-rc
  url_launcher: ^5.4.1
  fluttertoast: ^3.1.3
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
   - assets/
